/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mymp;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author Abhigna
 */
public class AddAccount extends javax.swing.JDialog {

    /**
     * Creates new form addacc
     */
    public AddAccount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ACCOUNTNUMBER = new javax.swing.JLabel();
        accnofield = new javax.swing.JTextField();
        USERNAME = new javax.swing.JLabel();
        usnfield = new javax.swing.JTextField();
        USERADDRESS = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        PHONENUMBER = new javax.swing.JLabel();
        phnofield = new javax.swing.JTextField();
        BALANCE = new javax.swing.JLabel();
        balfield = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        CANCEL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NEW ACCOUNT");
        setBounds(new java.awt.Rectangle(20, 20, 0, 0));
        setName("NEW ACCOUNT\n"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        ACCOUNTNUMBER.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ACCOUNTNUMBER.setText("ACCOUNT NUMBER");

        accnofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnofieldActionPerformed(evt);
            }
        });
        accnofield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accnofieldKeyTyped(evt);
            }
        });

        USERNAME.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        USERNAME.setText("USER NAME ");

        usnfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usnfieldActionPerformed(evt);
            }
        });
        usnfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usnfieldKeyPressed(evt);
            }
        });

        USERADDRESS.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        USERADDRESS.setText("USER ADDRESS");

        addressfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressfieldActionPerformed(evt);
            }
        });

        PHONENUMBER.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PHONENUMBER.setText("PHONE NUMBER");

        phnofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnofieldActionPerformed(evt);
            }
        });
        phnofield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phnofieldKeyPressed(evt);
            }
        });

        BALANCE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BALANCE.setText("BALANCE ");

        balfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balfieldActionPerformed(evt);
            }
        });
        balfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                balfieldKeyTyped(evt);
            }
        });

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        CANCEL.setText("CANCEL");
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ACCOUNTNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(accnofield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(usnfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(USERADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PHONENUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(phnofield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BALANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(balfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ACCOUNTNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accnofield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usnfield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(USERADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PHONENUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phnofield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BALANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balfield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void balfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balfieldActionPerformed

    private void usnfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usnfieldActionPerformed
       
    }//GEN-LAST:event_usnfieldActionPerformed

    private void addressfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressfieldActionPerformed

    private void phnofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnofieldActionPerformed
       
    }//GEN-LAST:event_phnofieldActionPerformed

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
        this.dispose();
    }//GEN-LAST:event_CANCELActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
       
        Connection conn;
        MyConnection addacc1 = new MyConnection();
        conn = addacc1.getConnection();
        String querys = "insert into customer1(cno,cname,caddress,cph,cbalance) values(?,?,?,?,?)";
        if(accnofield.getText().isEmpty() || usnfield.getText().isEmpty() || addressfield.getText().isEmpty() || phnofield.getText().isEmpty() ||  balfield.getText().isEmpty() ){
                JOptionPane.showMessageDialog(rootPane,"Please fill in the required information\n Account not created");
            }else{
        try{
            PreparedStatement pstmt = conn.prepareStatement(querys);
            
            pstmt.setString(1,accnofield.getText());
            pstmt.setString(2,usnfield.getText());
            pstmt.setString(3,addressfield.getText());
            pstmt.setString(4,phnofield.getText());
            pstmt.setString(5, balfield.getText());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"Account Created Successfully with the account number  "+accnofield.getText());
            }
        catch(SQLException ex){
            Logger.getLogger(AddAccount.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
    }//GEN-LAST:event_OKActionPerformed

    private void accnofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnofieldActionPerformed
     
    }//GEN-LAST:event_accnofieldActionPerformed

    private void accnofieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accnofieldKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (accnofield.getText()+evt.getKeyChar()).length()>2){
                evt.consume();
        }
     
        
    }//GEN-LAST:event_accnofieldKeyTyped

    private void usnfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usnfieldKeyPressed
        char c = evt.getKeyChar();
      
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            usnfield.setEditable(true);
        }else{
            usnfield.setEditable(false);
        }
    }//GEN-LAST:event_usnfieldKeyPressed

    private void phnofieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phnofieldKeyPressed
        String phoneNumber = phnofield.getText();
        int length = phoneNumber.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(length<10){
                phnofield.setEditable(true);
            }
            else{
                phnofield.setEditable(false);
        }
        }
            else{
                    if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ){
                        phnofield.setEditable(true);
                    }else{
                        usnfield.setEditable(false);
                    }
                    }
        
    }//GEN-LAST:event_phnofieldKeyPressed

    private void balfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_balfieldKeyTyped
         char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (balfield.getText()+evt.getKeyChar()).length()>10){
                evt.consume();
        }
    }//GEN-LAST:event_balfieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddAccount dialog = new AddAccount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACCOUNTNUMBER;
    private javax.swing.JLabel BALANCE;
    private javax.swing.JButton CANCEL;
    private javax.swing.JButton OK;
    private javax.swing.JLabel PHONENUMBER;
    private javax.swing.JLabel USERADDRESS;
    private javax.swing.JLabel USERNAME;
    private javax.swing.JTextField accnofield;
    private javax.swing.JTextField addressfield;
    private javax.swing.JTextField balfield;
    private javax.swing.JTextField phnofield;
    private javax.swing.JTextField usnfield;
    // End of variables declaration//GEN-END:variables
}
